services:
  gateway:
    image: ydiouy/medilabo-gateway:1.0.0
#    build: ./gateway/
    ports:
      - "127.0.0.1:9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - medilabo-network

  front:
    image: ydiouy/medilabo-front:1.0.0
#      context: ./front/
#      dockerfile: Dockerfile.test
#      target: development
    ports:
      - "9003:9003"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_ADDRESS=0.0.0.0
    depends_on:
      - gateway
    networks:
      - medilabo-network

  patient:
    image: ydiouy/medilabo-patient:1.0.0
#    build: ./patient/
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "127.0.0.1:9002:9002"
    depends_on:
      - gateway
    networks:
      - medilabo-network

  assessment:
    image: ydiouy/medilabo-assessment:1.0.0
#    build: ./assessment/
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      - gateway
    networks:
      - medilabo-network

  note:
    image: ydiouy/medilabo-note:1.0.0
#      build: ./note/
    depends_on:
      - note-mongo
      - gateway
    volumes:
      - note_data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - medilabo-network

  note-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
        - "127.0.0.1:27018:27017"
    volumes:
      - note_mongo_data_volume:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/
    networks:
      - medilabo-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://springuser:password@note-mongo:27017/admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    networks:
      - medilabo-network

volumes:
  note_data:
  note_mongo_data_volume:

networks:
  medilabo-network:
    driver: bridge
