server:
  port: 9001

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
#          default-filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
            - id: exemple-hello
#              uri: http://localhost:9002
              uri: lb://patient-service
              predicates:
                - Path=/api/patients/hello
              filters:
                - StripPrefix=2
#                - AddRequestHeader=X-Request-Example, Gateway-Request
#                - AddResponseHeader=X-Response-Example, Gateway-Response

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9004/eureka/

